---
- project:
    templates:
      - build-openstack-docs-pti
    check:
      jobs:
        - build-openstack-api-ref
        - build-openstack-releasenotes
        - openstack-tox-linters
        - openstack-tox-pep8
        - stx-devstack-metal:
            voting: false
    gate:
      jobs:
        - build-openstack-api-ref
        - build-openstack-releasenotes
        - openstack-tox-linters
        - openstack-tox-pep8
    post:
      jobs:
        - publish-stx-api-ref
        - publish-stx-tox
        - publish-stx-releasenotes

- job:
    name: stx-devstack-metal
    parent: stx-devstack-base
    timeout: 7800
    required-projects:
      - openstack/stx-update
      - openstack/stx-fault
    vars:
      tox_envlist: functional
      devstack_services:
        fm-common: true
        fm-api: true
        mtce: true
        mtce-compute: true
        mtce-control: true
        mtce-storage: true
        hbs: true
        pmon: true
        rmon: true
        hwmon: true
        mtclog: true
        mtcalarm: true
        fsmon: true
      devstack_plugins:
        stx-update: git://git.starlingx.io/stx-update
        stx-fault: git://git.starlingx.io/stx-fault
    files:
      - ^devstack/.*
