---
- project:
    templates:
      - check-requirements
    check:
      jobs:
        - openstack-tox-linters
        - openstack-tox-lower-constraints
        - openstack-tox-pep8:
            voting: false
    gate:
      jobs:
        - openstack-tox-linters
