#!/bin/bash
# Devstack settings

# Defaults
# --------

STX_METAL_NAME=stx-metal

######### Plugin Specific ##########
# Enable service for node type
enable_service $STX_METAL_NAME mtce_compute mtce_control mtce_storage

# Enable service for components
enable_service hbs

# run_process checks whether the service name is enabled or not
if is_service_enabled hbs; then
	# enable hbsAgent/hbsClient service as part of hbs service
    enable_service hbsAgent
	enable_service hbsClient
fi
if is_service_enabled mtce; then
	# enable mtcAgent/mtcClient service as part of mtce service
    enable_service mtcAgent
	enable_service mtcClient
fi

# Initial source of lib script
source $DEST/stx-metal/devstack/lib/stx-metal
