#!/bin/bash
# Devstack settings

# Servcies
# stx-metal - Overall enable for this plugin

# mtce
# mtce-control
# mtce-compute
# mtce-storage

# hbs
# pmon
# rmon
# hwmon
# mtclog
# mtcalarm
# fsmon

# Defaults
# --------

STX_METAL_NAME=stx-metal

######### Plugin Specific ##########
enable_service $STX_METAL_NAME

# Be careful to enable hostw, it will restart your host
# if some config is not correct
#enable_service hostw

if is_service_enabled mtce-compute; then
    # stx-update
    enable_service tsconfig
fi
# run_process checks whether the service name is enabled or not
if is_service_enabled hbs; then
    # enable hbsAgent/hbsClient service as part of hbs service
    enable_service hbs-agent
    enable_service hbs-client
fi
if is_service_enabled mtce; then
    # enable mtcAgent/mtcClient service as part of mtce service
    enable_service mtc-agent
    enable_service mtc-client
fi
if is_service_enabled hwmon && is_plugin_enabled stx-config; then
    enable_service sysinv
fi

# Initial source of lib script
source $DEST/stx-metal/devstack/lib/stx-metal
